/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package it.unitn.disi.acad.model.acad.provider;

import it.unitn.disi.acad.model.acad.util.AcadAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class AcadItemProviderAdapterFactory extends AcadAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection supportedTypes = new ArrayList();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public AcadItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.G_GenDispatch} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected G_GenDispatchItemProvider g_GenDispatchItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.G_GenDispatch}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createG_GenDispatchAdapter() {
		if (g_GenDispatchItemProvider == null) {
			g_GenDispatchItemProvider = new G_GenDispatchItemProvider(this);
		}

		return g_GenDispatchItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.G_CallTaking} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected G_CallTakingItemProvider g_CallTakingItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.G_CallTaking}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createG_CallTakingAdapter() {
		if (g_CallTakingItemProvider == null) {
			g_CallTakingItemProvider = new G_CallTakingItemProvider(this);
		}

		return g_CallTakingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.D_DataUpd} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected D_DataUpdItemProvider d_DataUpdItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.D_DataUpd}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createD_DataUpdAdapter() {
		if (d_DataUpdItemProvider == null) {
			d_DataUpdItemProvider = new D_DataUpdItemProvider(this);
		}

		return d_DataUpdItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.G_ResourceId} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected G_ResourceIdItemProvider g_ResourceIdItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.G_ResourceId}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createG_ResourceIdAdapter() {
		if (g_ResourceIdItemProvider == null) {
			g_ResourceIdItemProvider = new G_ResourceIdItemProvider(this);
		}

		return g_ResourceIdItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.G_ResourceMob} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected G_ResourceMobItemProvider g_ResourceMobItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.G_ResourceMob}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createG_ResourceMobAdapter() {
		if (g_ResourceMobItemProvider == null) {
			g_ResourceMobItemProvider = new G_ResourceMobItemProvider(this);
		}

		return g_ResourceMobItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.G_ObtainMap} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected G_ObtainMapItemProvider g_ObtainMapItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.G_ObtainMap}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createG_ObtainMapAdapter() {
		if (g_ObtainMapItemProvider == null) {
			g_ObtainMapItemProvider = new G_ObtainMapItemProvider(this);
		}

		return g_ObtainMapItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.G_IncidentUpd} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected G_IncidentUpdItemProvider g_IncidentUpdItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.G_IncidentUpd}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createG_IncidentUpdAdapter() {
		if (g_IncidentUpdItemProvider == null) {
			g_IncidentUpdItemProvider = new G_IncidentUpdItemProvider(this);
		}

		return g_IncidentUpdItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.D_MaxCalls} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected D_MaxCallsItemProvider d_MaxCallsItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.D_MaxCalls}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createD_MaxCallsAdapter() {
		if (d_MaxCallsItemProvider == null) {
			d_MaxCallsItemProvider = new D_MaxCallsItemProvider(this);
		}

		return d_MaxCallsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.G_RegCall} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected G_RegCallItemProvider g_RegCallItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.G_RegCall}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createG_RegCallAdapter() {
		if (g_RegCallItemProvider == null) {
			g_RegCallItemProvider = new G_RegCallItemProvider(this);
		}

		return g_RegCallItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.T_ConfirmCall} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected T_ConfirmCallItemProvider t_ConfirmCallItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.T_ConfirmCall}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createT_ConfirmCallAdapter() {
		if (t_ConfirmCallItemProvider == null) {
			t_ConfirmCallItemProvider = new T_ConfirmCallItemProvider(this);
		}

		return t_ConfirmCallItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.G_AssignIncident} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected G_AssignIncidentItemProvider g_AssignIncidentItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.G_AssignIncident}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createG_AssignIncidentAdapter() {
		if (g_AssignIncidentItemProvider == null) {
			g_AssignIncidentItemProvider = new G_AssignIncidentItemProvider(this);
		}

		return g_AssignIncidentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.T_SearchDuplic} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected T_SearchDuplicItemProvider t_SearchDuplicItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.T_SearchDuplic}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createT_SearchDuplicAdapter() {
		if (t_SearchDuplicItemProvider == null) {
			t_SearchDuplicItemProvider = new T_SearchDuplicItemProvider(this);
		}

		return t_SearchDuplicItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.T_CreateOrAssign} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected T_CreateOrAssignItemProvider t_CreateOrAssignItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.T_CreateOrAssign}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createT_CreateOrAssignAdapter() {
		if (t_CreateOrAssignItemProvider == null) {
			t_CreateOrAssignItemProvider = new T_CreateOrAssignItemProvider(this);
		}

		return t_CreateOrAssignItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.T_InputInfo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected T_InputInfoItemProvider t_InputInfoItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.T_InputInfo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createT_InputInfoAdapter() {
		if (t_InputInfoItemProvider == null) {
			t_InputInfoItemProvider = new T_InputInfoItemProvider(this);
		}

		return t_InputInfoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.T_DetectLoc} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected T_DetectLocItemProvider t_DetectLocItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.T_DetectLoc}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createT_DetectLocAdapter() {
		if (t_DetectLocItemProvider == null) {
			t_DetectLocItemProvider = new T_DetectLocItemProvider(this);
		}

		return t_DetectLocItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.T_SpecConfig} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected T_SpecConfigItemProvider t_SpecConfigItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.T_SpecConfig}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createT_SpecConfigAdapter() {
		if (t_SpecConfigItemProvider == null) {
			t_SpecConfigItemProvider = new T_SpecConfigItemProvider(this);
		}

		return t_SpecConfigItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.T_ConfIncident} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected T_ConfIncidentItemProvider t_ConfIncidentItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.T_ConfIncident}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createT_ConfIncidentAdapter() {
		if (t_ConfIncidentItemProvider == null) {
			t_ConfIncidentItemProvider = new T_ConfIncidentItemProvider(this);
		}

		return t_ConfIncidentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.T_DetBestAmb} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected T_DetBestAmbItemProvider t_DetBestAmbItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.T_DetBestAmb}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createT_DetBestAmbAdapter() {
		if (t_DetBestAmbItemProvider == null) {
			t_DetBestAmbItemProvider = new T_DetBestAmbItemProvider(this);
		}

		return t_DetBestAmbItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.T_InformStat} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected T_InformStatItemProvider t_InformStatItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.T_InformStat}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createT_InformStatAdapter() {
		if (t_InformStatItemProvider == null) {
			t_InformStatItemProvider = new T_InformStatItemProvider(this);
		}

		return t_InformStatItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.G_RouteAssist} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected G_RouteAssistItemProvider g_RouteAssistItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.G_RouteAssist}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createG_RouteAssistAdapter() {
		if (g_RouteAssistItemProvider == null) {
			g_RouteAssistItemProvider = new G_RouteAssistItemProvider(this);
		}

		return g_RouteAssistItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.D_DriverKnows} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected D_DriverKnowsItemProvider d_DriverKnowsItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.D_DriverKnows}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createD_DriverKnowsAdapter() {
		if (d_DriverKnowsItemProvider == null) {
			d_DriverKnowsItemProvider = new D_DriverKnowsItemProvider(this);
		}

		return d_DriverKnowsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.T_AcadAssists} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected T_AcadAssistsItemProvider t_AcadAssistsItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.T_AcadAssists}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createT_AcadAssistsAdapter() {
		if (t_AcadAssistsItemProvider == null) {
			t_AcadAssistsItemProvider = new T_AcadAssistsItemProvider(this);
		}

		return t_AcadAssistsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.T_StaffAssists} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected T_StaffAssistsItemProvider t_StaffAssistsItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.T_StaffAssists}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createT_StaffAssistsAdapter() {
		if (t_StaffAssistsItemProvider == null) {
			t_StaffAssistsItemProvider = new T_StaffAssistsItemProvider(this);
		}

		return t_StaffAssistsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.T_Feedback} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected T_FeedbackItemProvider t_FeedbackItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.T_Feedback}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createT_FeedbackAdapter() {
		if (t_FeedbackItemProvider == null) {
			t_FeedbackItemProvider = new T_FeedbackItemProvider(this);
		}

		return t_FeedbackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.D_GazetUpd} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected D_GazetUpdItemProvider d_GazetUpdItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.D_GazetUpd}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createD_GazetUpdAdapter() {
		if (d_GazetUpdItemProvider == null) {
			d_GazetUpdItemProvider = new D_GazetUpdItemProvider(this);
		}

		return d_GazetUpdItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.G_ManualMap} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected G_ManualMapItemProvider g_ManualMapItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.G_ManualMap}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createG_ManualMapAdapter() {
		if (g_ManualMapItemProvider == null) {
			g_ManualMapItemProvider = new G_ManualMapItemProvider(this);
		}

		return g_ManualMapItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.T_CheckGazet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected T_CheckGazetItemProvider t_CheckGazetItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.T_CheckGazet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createT_CheckGazetAdapter() {
		if (t_CheckGazetItemProvider == null) {
			t_CheckGazetItemProvider = new T_CheckGazetItemProvider(this);
		}

		return t_CheckGazetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.T_CheckPaper} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected T_CheckPaperItemProvider t_CheckPaperItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.T_CheckPaper}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createT_CheckPaperAdapter() {
		if (t_CheckPaperItemProvider == null) {
			t_CheckPaperItemProvider = new T_CheckPaperItemProvider(this);
		}

		return t_CheckPaperItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.G_DispExcept} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected G_DispExceptItemProvider g_DispExceptItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.G_DispExcept}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createG_DispExceptAdapter() {
		if (g_DispExceptItemProvider == null) {
			g_DispExceptItemProvider = new G_DispExceptItemProvider(this);
		}

		return g_DispExceptItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.G_MonitorRes} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected G_MonitorResItemProvider g_MonitorResItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.G_MonitorRes}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createG_MonitorResAdapter() {
		if (g_MonitorResItemProvider == null) {
			g_MonitorResItemProvider = new G_MonitorResItemProvider(this);
		}

		return g_MonitorResItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.G_UpdPosition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected G_UpdPositionItemProvider g_UpdPositionItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.G_UpdPosition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createG_UpdPositionAdapter() {
		if (g_UpdPositionItemProvider == null) {
			g_UpdPositionItemProvider = new G_UpdPositionItemProvider(this);
		}

		return g_UpdPositionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.D_MDTPos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected D_MDTPosItemProvider d_MDTPosItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.D_MDTPos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createD_MDTPosAdapter() {
		if (d_MDTPosItemProvider == null) {
			d_MDTPosItemProvider = new D_MDTPosItemProvider(this);
		}

		return d_MDTPosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.T_RadioPos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected T_RadioPosItemProvider t_RadioPosItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.T_RadioPos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createT_RadioPosAdapter() {
		if (t_RadioPosItemProvider == null) {
			t_RadioPosItemProvider = new T_RadioPosItemProvider(this);
		}

		return t_RadioPosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.D_MDTUse} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected D_MDTUseItemProvider d_MDTUseItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.D_MDTUse}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createD_MDTUseAdapter() {
		if (d_MDTUseItemProvider == null) {
			d_MDTUseItemProvider = new D_MDTUseItemProvider(this);
		}

		return d_MDTUseItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.T_MonitorStatus} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected T_MonitorStatusItemProvider t_MonitorStatusItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.T_MonitorStatus}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createT_MonitorStatusAdapter() {
		if (t_MonitorStatusItemProvider == null) {
			t_MonitorStatusItemProvider = new T_MonitorStatusItemProvider(this);
		}

		return t_MonitorStatusItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.T_DispStatus} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected T_DispStatusItemProvider t_DispStatusItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.T_DispStatus}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createT_DispStatusAdapter() {
		if (t_DispStatusItemProvider == null) {
			t_DispStatusItemProvider = new T_DispStatusItemProvider(this);
		}

		return t_DispStatusItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.T_DispDepArriv} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected T_DispDepArrivItemProvider t_DispDepArrivItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.T_DispDepArriv}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createT_DispDepArrivAdapter() {
		if (t_DispDepArrivItemProvider == null) {
			t_DispDepArrivItemProvider = new T_DispDepArrivItemProvider(this);
		}

		return t_DispDepArrivItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.T_ReplAmb} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected T_ReplAmbItemProvider t_ReplAmbItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.T_ReplAmb}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createT_ReplAmbAdapter() {
		if (t_ReplAmbItemProvider == null) {
			t_ReplAmbItemProvider = new T_ReplAmbItemProvider(this);
		}

		return t_ReplAmbItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.T_Except} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected T_ExceptItemProvider t_ExceptItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.T_Except}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createT_ExceptAdapter() {
		if (t_ExceptItemProvider == null) {
			t_ExceptItemProvider = new T_ExceptItemProvider(this);
		}

		return t_ExceptItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.T_ExceptQueue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected T_ExceptQueueItemProvider t_ExceptQueueItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.T_ExceptQueue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createT_ExceptQueueAdapter() {
		if (t_ExceptQueueItemProvider == null) {
			t_ExceptQueueItemProvider = new T_ExceptQueueItemProvider(this);
		}

		return t_ExceptQueueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.T_CloseIncident} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected T_CloseIncidentItemProvider t_CloseIncidentItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.T_CloseIncident}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createT_CloseIncidentAdapter() {
		if (t_CloseIncidentItemProvider == null) {
			t_CloseIncidentItemProvider = new T_CloseIncidentItemProvider(this);
		}

		return t_CloseIncidentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.S_FastDispatch} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected S_FastDispatchItemProvider s_FastDispatchItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.S_FastDispatch}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createS_FastDispatchAdapter() {
		if (s_FastDispatchItemProvider == null) {
			s_FastDispatchItemProvider = new S_FastDispatchItemProvider(this);
		}

		return s_FastDispatchItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.Q_Dispatch} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Q_DispatchItemProvider q_DispatchItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.Q_Dispatch}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createQ_DispatchAdapter() {
		if (q_DispatchItemProvider == null) {
			q_DispatchItemProvider = new Q_DispatchItemProvider(this);
		}

		return q_DispatchItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.S_FastAssist} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected S_FastAssistItemProvider s_FastAssistItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.S_FastAssist}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createS_FastAssistAdapter() {
		if (s_FastAssistItemProvider == null) {
			s_FastAssistItemProvider = new S_FastAssistItemProvider(this);
		}

		return s_FastAssistItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.Q_IncidResolv} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Q_IncidResolvItemProvider q_IncidResolvItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.Q_IncidResolv}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createQ_IncidResolvAdapter() {
		if (q_IncidResolvItemProvider == null) {
			q_IncidResolvItemProvider = new Q_IncidResolvItemProvider(this);
		}

		return q_IncidResolvItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.S_FastArriv} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected S_FastArrivItemProvider s_FastArrivItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.S_FastArriv}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createS_FastArrivAdapter() {
		if (s_FastArrivItemProvider == null) {
			s_FastArrivItemProvider = new S_FastArrivItemProvider(this);
		}

		return s_FastArrivItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.Q_AmbArriv} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Q_AmbArrivItemProvider q_AmbArrivItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.Q_AmbArriv}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createQ_AmbArrivAdapter() {
		if (q_AmbArrivItemProvider == null) {
			q_AmbArrivItemProvider = new Q_AmbArrivItemProvider(this);
		}

		return q_AmbArrivItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.S_LowCost} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected S_LowCostItemProvider s_LowCostItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.S_LowCost}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createS_LowCostAdapter() {
		if (s_LowCostItemProvider == null) {
			s_LowCostItemProvider = new S_LowCostItemProvider(this);
		}

		return s_LowCostItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.Q_MaxCost} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Q_MaxCostItemProvider q_MaxCostItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.Q_MaxCost}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createQ_MaxCostAdapter() {
		if (q_MaxCostItemProvider == null) {
			q_MaxCostItemProvider = new Q_MaxCostItemProvider(this);
		}

		return q_MaxCostItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.S_UserFriendly} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected S_UserFriendlyItemProvider s_UserFriendlyItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.S_UserFriendly}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createS_UserFriendlyAdapter() {
		if (s_UserFriendlyItemProvider == null) {
			s_UserFriendlyItemProvider = new S_UserFriendlyItemProvider(this);
		}

		return s_UserFriendlyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.Q_MaxTimeMsg} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Q_MaxTimeMsgItemProvider q_MaxTimeMsgItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.Q_MaxTimeMsg}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createQ_MaxTimeMsgAdapter() {
		if (q_MaxTimeMsgItemProvider == null) {
			q_MaxTimeMsgItemProvider = new Q_MaxTimeMsgItemProvider(this);
		}

		return q_MaxTimeMsgItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.AR1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AR1ItemProvider ar1ItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.AR1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAR1Adapter() {
		if (ar1ItemProvider == null) {
			ar1ItemProvider = new AR1ItemProvider(this);
		}

		return ar1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.AR2} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AR2ItemProvider ar2ItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.AR2}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAR2Adapter() {
		if (ar2ItemProvider == null) {
			ar2ItemProvider = new AR2ItemProvider(this);
		}

		return ar2ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.AR3} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AR3ItemProvider ar3ItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.AR3}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAR3Adapter() {
		if (ar3ItemProvider == null) {
			ar3ItemProvider = new AR3ItemProvider(this);
		}

		return ar3ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.AR4} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AR4ItemProvider ar4ItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.AR4}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAR4Adapter() {
		if (ar4ItemProvider == null) {
			ar4ItemProvider = new AR4ItemProvider(this);
		}

		return ar4ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.AR5} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AR5ItemProvider ar5ItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.AR5}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAR5Adapter() {
		if (ar5ItemProvider == null) {
			ar5ItemProvider = new AR5ItemProvider(this);
		}

		return ar5ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.AR6} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AR6ItemProvider ar6ItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.AR6}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAR6Adapter() {
		if (ar6ItemProvider == null) {
			ar6ItemProvider = new AR6ItemProvider(this);
		}

		return ar6ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.AR7} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AR7ItemProvider ar7ItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.AR7}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAR7Adapter() {
		if (ar7ItemProvider == null) {
			ar7ItemProvider = new AR7ItemProvider(this);
		}

		return ar7ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.AR8} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AR8ItemProvider ar8ItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.AR8}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAR8Adapter() {
		if (ar8ItemProvider == null) {
			ar8ItemProvider = new AR8ItemProvider(this);
		}

		return ar8ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.AR9} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AR9ItemProvider ar9ItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.AR9}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAR9Adapter() {
		if (ar9ItemProvider == null) {
			ar9ItemProvider = new AR9ItemProvider(this);
		}

		return ar9ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.AR10} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AR10ItemProvider ar10ItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.AR10}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAR10Adapter() {
		if (ar10ItemProvider == null) {
			ar10ItemProvider = new AR10ItemProvider(this);
		}

		return ar10ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.AR11} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AR11ItemProvider ar11ItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.AR11}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAR11Adapter() {
		if (ar11ItemProvider == null) {
			ar11ItemProvider = new AR11ItemProvider(this);
		}

		return ar11ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.AR12} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AR12ItemProvider ar12ItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.AR12}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAR12Adapter() {
		if (ar12ItemProvider == null) {
			ar12ItemProvider = new AR12ItemProvider(this);
		}

		return ar12ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.AR13} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AR13ItemProvider ar13ItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.AR13}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAR13Adapter() {
		if (ar13ItemProvider == null) {
			ar13ItemProvider = new AR13ItemProvider(this);
		}

		return ar13ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.AR14} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AR14ItemProvider ar14ItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.AR14}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAR14Adapter() {
		if (ar14ItemProvider == null) {
			ar14ItemProvider = new AR14ItemProvider(this);
		}

		return ar14ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.AR15} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AR15ItemProvider ar15ItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.AR15}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAR15Adapter() {
		if (ar15ItemProvider == null) {
			ar15ItemProvider = new AR15ItemProvider(this);
		}

		return ar15ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link it.unitn.disi.acad.model.acad.AcadGoalModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AcadGoalModelItemProvider acadGoalModelItemProvider;

	/**
	 * This creates an adapter for a {@link it.unitn.disi.acad.model.acad.AcadGoalModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAcadGoalModelAdapter() {
		if (acadGoalModelItemProvider == null) {
			acadGoalModelItemProvider = new AcadGoalModelItemProvider(this);
		}

		return acadGoalModelItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class) || (((Class)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (g_GenDispatchItemProvider != null) g_GenDispatchItemProvider.dispose();
		if (g_CallTakingItemProvider != null) g_CallTakingItemProvider.dispose();
		if (d_DataUpdItemProvider != null) d_DataUpdItemProvider.dispose();
		if (g_ResourceIdItemProvider != null) g_ResourceIdItemProvider.dispose();
		if (g_ResourceMobItemProvider != null) g_ResourceMobItemProvider.dispose();
		if (g_ObtainMapItemProvider != null) g_ObtainMapItemProvider.dispose();
		if (g_IncidentUpdItemProvider != null) g_IncidentUpdItemProvider.dispose();
		if (d_MaxCallsItemProvider != null) d_MaxCallsItemProvider.dispose();
		if (g_RegCallItemProvider != null) g_RegCallItemProvider.dispose();
		if (t_ConfirmCallItemProvider != null) t_ConfirmCallItemProvider.dispose();
		if (g_AssignIncidentItemProvider != null) g_AssignIncidentItemProvider.dispose();
		if (t_SearchDuplicItemProvider != null) t_SearchDuplicItemProvider.dispose();
		if (t_CreateOrAssignItemProvider != null) t_CreateOrAssignItemProvider.dispose();
		if (t_InputInfoItemProvider != null) t_InputInfoItemProvider.dispose();
		if (t_DetectLocItemProvider != null) t_DetectLocItemProvider.dispose();
		if (t_SpecConfigItemProvider != null) t_SpecConfigItemProvider.dispose();
		if (t_ConfIncidentItemProvider != null) t_ConfIncidentItemProvider.dispose();
		if (t_DetBestAmbItemProvider != null) t_DetBestAmbItemProvider.dispose();
		if (t_InformStatItemProvider != null) t_InformStatItemProvider.dispose();
		if (g_RouteAssistItemProvider != null) g_RouteAssistItemProvider.dispose();
		if (d_DriverKnowsItemProvider != null) d_DriverKnowsItemProvider.dispose();
		if (t_AcadAssistsItemProvider != null) t_AcadAssistsItemProvider.dispose();
		if (t_StaffAssistsItemProvider != null) t_StaffAssistsItemProvider.dispose();
		if (t_FeedbackItemProvider != null) t_FeedbackItemProvider.dispose();
		if (d_GazetUpdItemProvider != null) d_GazetUpdItemProvider.dispose();
		if (g_ManualMapItemProvider != null) g_ManualMapItemProvider.dispose();
		if (t_CheckGazetItemProvider != null) t_CheckGazetItemProvider.dispose();
		if (t_CheckPaperItemProvider != null) t_CheckPaperItemProvider.dispose();
		if (g_DispExceptItemProvider != null) g_DispExceptItemProvider.dispose();
		if (g_MonitorResItemProvider != null) g_MonitorResItemProvider.dispose();
		if (g_UpdPositionItemProvider != null) g_UpdPositionItemProvider.dispose();
		if (d_MDTPosItemProvider != null) d_MDTPosItemProvider.dispose();
		if (t_RadioPosItemProvider != null) t_RadioPosItemProvider.dispose();
		if (d_MDTUseItemProvider != null) d_MDTUseItemProvider.dispose();
		if (t_MonitorStatusItemProvider != null) t_MonitorStatusItemProvider.dispose();
		if (t_DispStatusItemProvider != null) t_DispStatusItemProvider.dispose();
		if (t_DispDepArrivItemProvider != null) t_DispDepArrivItemProvider.dispose();
		if (t_ReplAmbItemProvider != null) t_ReplAmbItemProvider.dispose();
		if (t_ExceptItemProvider != null) t_ExceptItemProvider.dispose();
		if (t_ExceptQueueItemProvider != null) t_ExceptQueueItemProvider.dispose();
		if (t_CloseIncidentItemProvider != null) t_CloseIncidentItemProvider.dispose();
		if (s_FastDispatchItemProvider != null) s_FastDispatchItemProvider.dispose();
		if (q_DispatchItemProvider != null) q_DispatchItemProvider.dispose();
		if (s_FastAssistItemProvider != null) s_FastAssistItemProvider.dispose();
		if (q_IncidResolvItemProvider != null) q_IncidResolvItemProvider.dispose();
		if (s_FastArrivItemProvider != null) s_FastArrivItemProvider.dispose();
		if (q_AmbArrivItemProvider != null) q_AmbArrivItemProvider.dispose();
		if (s_LowCostItemProvider != null) s_LowCostItemProvider.dispose();
		if (q_MaxCostItemProvider != null) q_MaxCostItemProvider.dispose();
		if (s_UserFriendlyItemProvider != null) s_UserFriendlyItemProvider.dispose();
		if (q_MaxTimeMsgItemProvider != null) q_MaxTimeMsgItemProvider.dispose();
		if (ar1ItemProvider != null) ar1ItemProvider.dispose();
		if (ar2ItemProvider != null) ar2ItemProvider.dispose();
		if (ar3ItemProvider != null) ar3ItemProvider.dispose();
		if (ar4ItemProvider != null) ar4ItemProvider.dispose();
		if (ar5ItemProvider != null) ar5ItemProvider.dispose();
		if (ar6ItemProvider != null) ar6ItemProvider.dispose();
		if (ar7ItemProvider != null) ar7ItemProvider.dispose();
		if (ar8ItemProvider != null) ar8ItemProvider.dispose();
		if (ar9ItemProvider != null) ar9ItemProvider.dispose();
		if (ar10ItemProvider != null) ar10ItemProvider.dispose();
		if (ar11ItemProvider != null) ar11ItemProvider.dispose();
		if (ar12ItemProvider != null) ar12ItemProvider.dispose();
		if (ar13ItemProvider != null) ar13ItemProvider.dispose();
		if (ar14ItemProvider != null) ar14ItemProvider.dispose();
		if (ar15ItemProvider != null) ar15ItemProvider.dispose();
		if (acadGoalModelItemProvider != null) acadGoalModelItemProvider.dispose();
	}

}
