<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="scheduler" nsURI="http://disi.unitn.it/zanshin/1.0/scheduler"
    nsPrefix="scheduler">
  <eClassifiers xsi:type="ecore:EClass" name="SchedulerGoalModel" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//GoalModel"/>
  <eClassifiers xsi:type="ecore:EClass" name="G_SchedMeet" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//HardGoal"/>
  <eClassifiers xsi:type="ecore:EClass" name="T_CharactMeet" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//Task"/>
  <eClassifiers xsi:type="ecore:EClass" name="G_CollectTime" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//HardGoal"/>
  <eClassifiers xsi:type="ecore:EClass" name="T_CallPartic" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//Task"/>
  <eClassifiers xsi:type="ecore:EClass" name="T_EmailPartic" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//Task"/>
  <eClassifiers xsi:type="ecore:EClass" name="G_CollectAuto" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//HardGoal"/>
  <eClassifiers xsi:type="ecore:EClass" name="D_ParticUseCal" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//DomainAssumption"/>
  <eClassifiers xsi:type="ecore:EClass" name="T_CollectCal" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//Task"/>
  <eClassifiers xsi:type="ecore:EClass" name="G_FindRoom" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//HardGoal"/>
  <eClassifiers xsi:type="ecore:EClass" name="G_UseLocal" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//HardGoal"/>
  <eClassifiers xsi:type="ecore:EClass" name="G_FindLocal" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//HardGoal"/>
  <eClassifiers xsi:type="ecore:EClass" name="T_GetSuggest" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//Task"/>
  <eClassifiers xsi:type="ecore:EClass" name="T_ListAvail" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//Task"/>
  <eClassifiers xsi:type="ecore:EClass" name="D_LocalAvail" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//DomainAssumption"/>
  <eClassifiers xsi:type="ecore:EClass" name="G_BookRoom" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//HardGoal"/>
  <eClassifiers xsi:type="ecore:EClass" name="T_UseAvail" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//Task"/>
  <eClassifiers xsi:type="ecore:EClass" name="T_CancelLess" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//Task"/>
  <eClassifiers xsi:type="ecore:EClass" name="T_CallPartner" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//Task"/>
  <eClassifiers xsi:type="ecore:EClass" name="T_CallHotel" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//Task"/>
  <eClassifiers xsi:type="ecore:EClass" name="G_ChooseSched" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//HardGoal"/>
  <eClassifiers xsi:type="ecore:EClass" name="T_SchedManual" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//Task"/>
  <eClassifiers xsi:type="ecore:EClass" name="T_SchedSystem" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//Task"/>
  <eClassifiers xsi:type="ecore:EClass" name="G_ManageMeet" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//HardGoal"/>
  <eClassifiers xsi:type="ecore:EClass" name="T_CancelMeet" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//Task"/>
  <eClassifiers xsi:type="ecore:EClass" name="T_ConfirmOcc" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//Task"/>
  <eClassifiers xsi:type="ecore:EClass" name="S_LowCost" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//Softgoal"/>
  <eClassifiers xsi:type="ecore:EClass" name="Q_CostLess100" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//QualityConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="S_GoodPartic" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//Softgoal"/>
  <eClassifiers xsi:type="ecore:EClass" name="Q_Min90pctPart" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//QualityConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="S_FastSched" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//Softgoal"/>
  <eClassifiers xsi:type="ecore:EClass" name="Q_Sched1Day" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//QualityConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="AR1" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//AwReq"/>
  <eClassifiers xsi:type="ecore:EClass" name="AR2" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//AwReq"/>
  <eClassifiers xsi:type="ecore:EClass" name="AR3" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//AwReq"/>
  <eClassifiers xsi:type="ecore:EClass" name="AR4" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//AwReq"/>
  <eClassifiers xsi:type="ecore:EClass" name="AR5" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//AwReq"/>
  <eClassifiers xsi:type="ecore:EClass" name="AR6" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//AwReq"/>
  <eClassifiers xsi:type="ecore:EClass" name="AR7" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//AwReq"/>
  <eClassifiers xsi:type="ecore:EClass" name="AR8" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//AwReq"/>
  <eClassifiers xsi:type="ecore:EClass" name="AR9" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//AwReq"/>
  <eClassifiers xsi:type="ecore:EClass" name="AR10" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//AwReq"/>
  <eClassifiers xsi:type="ecore:EClass" name="AR11" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//AwReq"/>
  <eClassifiers xsi:type="ecore:EClass" name="AR12" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//AwReq"/>
  <eClassifiers xsi:type="ecore:EClass" name="AR13" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//AwReq"/>
  <eClassifiers xsi:type="ecore:EClass" name="AR14" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//AwReq"/>
  <eClassifiers xsi:type="ecore:EClass" name="CV_FhM" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//Parameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="CV_RfM" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//Parameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="CV_MCA" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//Parameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="CV_RF" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//Parameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="CV_VPA" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//Parameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="VP1" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//Parameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="VP2" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//Parameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="VP3" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//Parameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="VP4" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//Parameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="VP5" eSuperTypes="../../../../../../../../../it.unitn.disi.zanshin.core/META-INF/gore.ecore#//Parameter"/>
</ecore:EPackage>
